
project_id = "bhhgesyiucnxxhsmrphn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_parameter_max_connections = "25"

[realtime]
enabled = true
ip_version = "ipv6"
tenants = [
  { name = "realtime-dev", db_name = "postgres", db_host = "localhost", db_port = 54322, ip_version = "ipv4" },
]

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
only_if_email_enabled = true

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54326
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://bhhgesyiucnxxhsmrphn.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[auth.email]
enabled = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enabled = false

[edge_runtime]
enabled = true
ip_version = "ipv4"
port = 54327
inspector_port = 8083
