
import Logo from "@/components/Logo";
import { Button } from "@/components/ui/button";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Logo />
          <nav className="hidden md:flex items-center space-x-6">
            <a href="/" className="text-muted-foreground hover:text-foreground transition-colors">Home</a>
            <a href="/#features" className="text-muted-foreground hover:text-foreground transition-colors">Features</a>
            <a href="/blog" className="text-muted-foreground hover:text-foreground transition-colors">Blog</a>
            <a href="/#pricing" className="text-muted-foreground hover:text-foreground transition-colors">Pricing</a>
          </nav>
          <Button variant="default" size="lg">Get Started</Button>
        </div>
      </header>

      {/* Content */}
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: January 15, 2025</p>
        
        <div className="prose prose-lg max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-semibold mb-4">Agreement to Terms</h2>
            <p>
              By accessing and using AI Affiliate Pro, you accept and agree to be bound by the terms and provision 
              of this agreement. These Terms of Service govern your use of our Chrome extension and related services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Description of Service</h2>
            <p>
              AI Affiliate Pro is a Chrome extension that uses artificial intelligence to generate Amazon product 
              reviews, comparisons, and affiliate marketing content. Our service requires:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>A valid Chrome browser installation</li>
              <li>An active internet connection</li>
              <li>Your own OpenAI API key for content generation</li>
              <li>Compliance with Amazon's affiliate marketing policies</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">User Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the service lawfully and ethically</li>
              <li>Comply with Amazon Associates Program terms</li>
              <li>Not generate false or misleading product reviews</li>
              <li>Properly disclose affiliate relationships as required by FTC guidelines</li>
              <li>Respect intellectual property rights</li>
              <li>Not attempt to reverse engineer or copy our technology</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Content and Intellectual Property</h2>
            <p>
              Content generated by AI Affiliate Pro is provided for your use in accordance with these terms. 
              You are responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Reviewing and editing all generated content before publication</li>
              <li>Ensuring accuracy of product information</li>
              <li>Complying with applicable laws and regulations</li>
              <li>Respecting third-party intellectual property rights</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Payment and Refunds</h2>
            <p>
              AI Affiliate Pro operates on a one-time payment model:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>All payments are processed securely through third-party providers</li>
              <li>Refunds are available within 30 days of purchase</li>
              <li>Refund requests must be submitted through our support channels</li>
              <li>No refunds for API costs incurred with OpenAI</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Limitation of Liability</h2>
            <p>
              AI Affiliate Pro shall not be liable for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Any indirect, incidental, or consequential damages</li>
              <li>Loss of profits or revenue from affiliate marketing activities</li>
              <li>Content accuracy or compliance with third-party policies</li>
              <li>Third-party service interruptions (Amazon, OpenAI, etc.)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Termination</h2>
            <p>
              We may terminate or suspend your access to our service immediately, without prior notice, 
              for violation of these terms or for any other reason at our sole discretion.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of our service 
              constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Contact Information</h2>
            <p>
              Questions about these Terms of Service should be sent to:
            </p>
            <p>
              Email: legal@aiaffiliatepro.com<br/>
              Address: [Your Business Address]
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Terms;
