// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhhgesyiucnxxhsmrphn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoaGdlc3lpdWNueHhoc21ycGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3OTUzMDgsImV4cCI6MjA3MDM3MTMwOH0.vWeJQkXqFkZafsJsml_r7GK3yz5zJDOuhIWZCR-MUA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});